#define ENFUSION_WORLD 0x105C89C // DayZ->
#define ENFUSION_NETWORKMANAGER 0x10462D0 // DayZ->
#define ENFUSION_CGAME 0x104209C // DayZ->
#define ENFUSION_CREATEVEHICLE 0xA98DD0 // DayZ->

#define ENFUSION_NETWORKCLIENT 0x24 // NetworkManager->
#define ENFUSION_NETWORKCLIENT_SERVERNAME 0x2B8 // NetworkClient->
#define ENFUSION_NETWORKCLIENT_LOCALPLAYERNAME 0x2D0 // NetworkClient->
#define ENFUSION_NETWORKCLIENT_SCOREBOARD 0xC // NetworkClient->
#define ENFUSION_NETWORKCLIENT_PLAYERIDENTITY_SIZE 0xF0 // PlayerIdentity->
#define ENFUSION_NETWORKCLIENT_PLAYERIDENTITY_NETWORKID 0xC // PlayerIdentity->
#define ENFUSION_NETWORKCLIENT_PLAYERIDENTITY_STEAMID 0x4C // PlayerIdentity->
#define ENFUSION_NETWORKCLIENT_PLAYERIDENTITY_PLAYERNAME 0x88 // PlayerIdentity->

#define ENFUSION_WORLD_TERRAINGRID 0x17E0 // World-> *no grass*
#define ENFUSION_WORLD_TIME 0x16A4 // World-> *always day*
#define ENFUSION_WORLD_CAMERAON 0x1658 // World-> *local player pointer*
#define ENFUSION_WORLD_REALPLAYER 0x1662 // Camera-> *actual local player*
#define ENFUSION_WORLD_LATITUDE 0x16A4 // World->

#define ENFUSION_WORLD_CAMERA 0x114 // World-> *transformations, used for ESP and speedhack*

#define ENFUSION_WORLD_NEARANIMALTABLE 0xA3C // World-> *contains nearby entities >1000m*
#define ENFUSION_WORLD_FARANIMALTABLE 0xAE4 // World-> *contains far away entites <1000m*
#define ENFUSION_WORLD_SLOWANIMALTABLE 0x12CC // World->
#define ENFUSION_WORLD_ITEMTABLE 0x12EC // World-> *item esp*
#define ENFUSION_WORLD_DROPPEDITEMTABLE 0xF84 // World-> 
#define ENFUSION_WORLD_BULLETTABLE 0x990 // World-> *murder mode*

#define ENFUSION_CAMERA_VIEWRIGHT 0x4 // Camera->
#define ENFUSION_CAMERA_VIEWUP 0x10 // Camera->
#define ENFUSION_CAMERA_VIEWFORWARD 0x1C // Camera->
#define ENFUSION_CAMERA_VIEWTRANSLATION 0x28 // Camera->
#define ENFUSION_CAMERA_VIEWPORTSIZE 0x54 // Camera->
#define ENFUSION_CAMERA_PROJECTION_D1 0xCC // Camera->
#define ENFUSION_CAMERA_PROJECTION_D2 0xD8 // Camera->

#define ENFUSION_ENTITY_BASEENTITY 0x58 // Entity->
#define ENFUSION_ENTITY_FUTUREVISUALSTATE 0x84 // Entity->
#define ENFUSION_ENTITY_RENDERERVISUALSTATE 0xC8 // Entity->
#define ENFUSION_ENTITY_ENTITYTYPE 0x7C // Entity->
#define ENFUSION_ENTITY_DRIVERYENTITY 0xBD8 // Entity->
#define ENFUSION_ENTITY_INTEMINHANDS 0xC40 // Entity->
#define ENFUSION_ENTITY_NETWORKID 0x9F8 // Entity->
#define ENFUSION_ENTITY_STANCE 0x14E0 // Entity->
#define ENFUSION_ENTITY_ISDEAD 0x2D0 // Entity->

#define ENFUSION_PLAYER_FUTUREVISUALSTATE 0x34 // LocalPlayer->Entity->  *stores local coordinates* 
#define ENFUSION_PLAYER_RENDERERVISUALSTATE 0x78 // LocalPlayer->Entity-> 
#define ENFUSION_PLAYER_RECOIL 0xDCC // LocalPlayer->Entity->
#define ENFUSION_PLAYER_FATIGUE 0xDE8 // LocalPlayer->Entity->
#define ENFUSION_PLAYER_FATIGUELEFT 0xDEC // LocalPlayer->Entity->
#define ENFUSION_PLAYER_SIMULATION 0x42C // LocalPlayer->Entity->

#define ENFUSION_VISUALSTATE_POSITION 0x28 // VisualState-> *your coordinates in X, Y, Z* - FutureVisualState
#define ENFUSION_VISUALSTATE_HEADPOSITION 0x130 // VisualState->
#define ENFUSION_VISUALSTATE_CHESTPOSITION 0x13C // VisualState->
#define ENFUSION_VISUALSTATE_VELOCITY 0x48 // VisualState->

#pragma once
